### ISSUE TITLE
Migration Stuff

### ISSUE THREAD

**Issue by MiniDigger** [VoxelGamesLib/VoxelGamesLibv2#1]
- [x] copy everything into the project, lol
- [x] migrate event api
- [x] migrate command api
   - [ ] test all commands/subcommand/completions
   - [ ] add help commands
- [x] migrate/rewrite lang api (and use text over bungee-chat while at it)
- [x] migrate scoreboard api
- [ ] migrate/rewrite persistence (see #41)
- [ ] let config use gson versioning

**Comment by itsaphel** [comment]
We're well past the migration stage.

Closing this in favour of separate issues for things that still aren't completed.
