### ISSUE TITLE
take a look at https://www.spigotmc.org/resources/api-menubuilder.12995/

### ISSUE THREAD

**Issue by MiniDigger** [VoxelGamesLib/VoxelGamesLibv2#100]

**Comment by Sxtanna** [comment]
https://github.com/timtomtim7/ChatMenuAPI

I would highly recommend we go for this for menus in the chat.

**Comment by MiniDigger** [comment]
@Sxtanna I really like the concept of that, I really hate how they used reflection to access chat packets. I think ill rewrite it to protocollib
