### ISSUE TITLE
MySQL SSL warning

### ISSUE THREAD

**Issue by MiniDigger** [VoxelGamesLib/VoxelGamesLibv2#40]
Wed Jun 21 21:05:43 CEST 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.

**Comment by LordRobust** [comment]
What's wrong with the warning?

**Comment by MiniDigger** [comment]
I think I have fixed this one already, I'll check later

**Comment by LordRobust** [comment]
Did you fix this, @MiniDigger

**Comment by MiniDigger** [comment]
yes, by disabling ssl :D
