### ISSUE TITLE
Hibernate models

### ISSUE THREAD

**Issue by itsaphel** [VoxelGamesLib/VoxelGamesLibv2#41]
Time to start creating models, or "entities" rather, for various things.

- [x] GamePlayer
- [ ] Games (with their statistics and relevant data)

**Comment by LordRobust** [comment]
added todos for games;

0010826c579d606daa32ba3dbe0773aab3f91def (mainly persist the players and spectators, setup relations for to the User entity). might be useful to make channels persistable as well, then set up a Game relation with a Channel

having entity on AbstractGame might not allow custom fields from extending games to sync. @MiniDigger solutions?
