### ISSUE TITLE
Make clicking on the game announce message make you join the game

### ISSUE THREAD

**Issue by MiniDigger** [VoxelGamesLib/VoxelGamesLibv2#52]

**Comment by LordRobust** [comment]
can't click join message either.

**Comment by MiniDigger** [comment]
started to work on that in c8a9c0752c4248141faa49eabc6079b5e07cb2b0  
currently leads to /vote 1 getting displayed in chat when you click on the vote message

**Comment by MiniDigger** [comment]
vote works as of 1033e78b66d59bc2641287098a88a3eb56250009 we need commands stuff to join a game by ID or smth

**Comment by MiniDigger** [comment]
Fully done now
