### ISSUE TITLE
Ideology regarding game designers, game developers, map devs

### ISSUE THREAD

**Issue by itsaphel** [VoxelGamesLib/VoxelGamesLibv2#69]
Adjust ideology:

Game developers directly use VoxelGamesLib to program the gamemode and its logic
Game designers adjust the gamemode and can easily add things like kits, adjust game phases, durations, etc (all without any developers needed)
Map designers create maps and use the VGL world system to package them up

Eventually, things like https://github.com/LordRobust/troubleinminecraft/issues/2 should be created by game designers too. They should be able to add basic effects to create custom tools.

VGL should provide a friendly interface for developers to assign variables that end up being json files where game designers can add onto.

**Comment by MiniDigger** [comment]
Every var annotated with @exposed in a feature will end up in the game definiton

**Comment by LordRobust** [comment]
It's a bit heavy to have shop items all in one game definition file.

We need a directory for them, like you did with kits, but VGL should provide an easy interface to do that.

**Comment by MiniDigger** [comment]
The game definiton will be heavy anyways, if ppl use a proper json editor they can just fold stuff. 
I think that a shop is just to specify to have a folder. 
You should just use a kit anyways. Currently a kit is a map int itemstack and a name.
