### ISSUE TITLE
Revert player state when a game ends

### ISSUE THREAD

**Issue by itsaphel** [VoxelGamesLib/VoxelGamesLibv2#78]
A player's gamemode should be cleared, they should be healed, fed, inventory cleared, XP reset, etc... when they leave a game.

Revert a player to their pre-game state.

**Comment by MiniDigger** [comment]
Do we want to revert or reset? Revert would be set back to how he was before he join, reset would reset him to empty inv XP full health etc. 
Reset is easier, revert prolly better

**Comment by itsaphel** [comment]
Let's revert
