### ISSUE TITLE
Give markers a vgl:%gamemode% prefix

### ISSUE THREAD

**Issue by itsaphel** [VoxelGamesLib/VoxelGamesLibv2#79]
Prevents any clashes with legitimate skulls. Also allows for categorisation.

I think you might've done this already. Worth tracking just so we can iron down the new syntax for use when working with markers, @MiniDigger

**Comment by MiniDigger** [comment]
I just added a vgl prefix the other day. 
I don't think vgl gamemode is nessasary since multiple gamemodes use the same markers (think spawn). 
It could make sense to bind them to features.
