### ISSUE TITLE
spectator handling is borked

### ISSUE THREAD

**Issue by MiniDigger** [VoxelGamesLib/VoxelGamesLibv2#81]
maybe we should add a spectate feature to handle all that stuff?

**Comment by itsaphel** [comment]
whats borked about it?

**Comment by itsaphel** [comment]
a spectator feature would be good in the sense that some games can disable spectating by not including the feature, but it would mean altering a lot of code.

spectating is a bit too bulky to be feature-specific. it should remain associated with the game/phase, tbh

**Comment by MiniDigger** [comment]
all gameplay aspects of spectating will be handled by a feature.
