### ISSUE TITLE
Add a custom Bukkit event: PlayerKillPlayerEvent

### ISSUE THREAD

**Issue by spammy23** [VoxelGamesLib/VoxelGamesLibv2#82]

**Comment by itsaphel** [comment]
Not going to add this to the core for the time being. Events like these, where they reduce some code (fetching a user) will end up meaning, really, we need to do this for a *lot* of Bukkit events, at least every Bukkit event that could involve more than one User. It becomes difficult to maintain and inconsistent.

At this stage, there's some bigger priorities in the project. This may be looked into again in the future, but for now, it's not worth it.
