### ISSUE TITLE
add JSR-305 nullability annotations

### ISSUE THREAD

**Issue by Redrield** [VoxelGamesLib/VoxelGamesLibv2#84]
Would really help with development, since you don't need to juggle the possibility of null parameters to things

Also it would really help me, these platform types are killing me :(

**Comment by itsaphel** [comment]
There's quite a few spotted around. We'll work on keeping it consistent around the project. Optionals are also used across the project.

**Comment by MiniDigger** [comment]
I created an intellij plugin to help highlight such issues:
https://github.com/MiniDigger/MiniPlugin
turns out we are missing quite a few, anybody wants to volunteer?...
![https://i.imgur.com/rDZw4AJ.png](https://i.imgur.com/rDZw4AJ.png)

**Comment by MiniDigger** [comment]
uuf, done.
