### ISSUE TITLE
Messages aren't sent in selected language

### ISSUE THREAD

**Issue by spammy23** [VoxelGamesLib/VoxelGamesLibv2#89]
It fires as if the user were running /lang

**Comment by itsaphel** [comment]
Should be fixed in https://github.com/VoxelGamesLib/VoxelGamesLibv2/commit/d670cbfeb95253cab0ef1578d29cc22b574eb35d

Please test

**Comment by spammy23** [comment]
As of now the issue not been fixed still persists.
