### ISSUE TITLE
Inventory API needs its own "Item" class

### ISSUE THREAD

**Issue by itsaphel** [VoxelGamesLib/VoxelGamesLibv2#97]
With normal inventories, the current system works fine, however with PagedInventory it will not work, since the same itemstack over multiple pages will just mess up.

By using an "Item" class and creating that instead, and adding a clickaction to that, we can work around the issue.

Also, a pro of this is that you can have the same itemstack in any kind of inventory and still have a unique click action.

**Comment by itsaphel** [comment]
Use slot IDs as identifiers instead, maybe?

**Comment by MiniDigger** [comment]
Might be worth looking at my old implementation 
https://github.com/MiniDigger/Core/tree/master/C_CraftCore/src/main/java/me/MiniDigger/CraftCore/Menu
https://github.com/MiniDigger/Core/tree/master/C_API/src/main/java/me/MiniDigger/Core/Menu
