### ISSUE TITLE
Game leaving is borked

### ISSUE THREAD

**Issue by itsaphel** [VoxelGamesLib/VoxelGamesLibv2#98]
Doesn't really do anything. You do everything on game stop.

**Comment by MiniDigger** [comment]
thats not true, game end does nothing to the player other than calling Game#leave, your game leave command also calls Game#leave.
needs further investigation

**Comment by MiniDigger** [comment]
hopefully fixed by 8de119d08320f3b4b4f2a8962bf8fb9719d7e7eb
